#setup and import libraries

import pandas as pd 

#function to split space delimited dataframe columns
#as generated by multi-selects in an ona form
def split_space_delimited(df,col):

	"""Function to parse space-delimited data in a DataFrame column.

	Will split columns into multiple columns and return a copy of original
	dataframe with new columns added.  Drops rows where col to split is null."""

	#begin by removing null values of the column to split from the dataframe
	df_notnull = df.loc[df[col].notnull()]
	df_notnull = df_notnull.reset_index().drop('index',axis=1)

	#create dataframe of space-delimited values in column
	df_split = pd.DataFrame(df_notnull[col].str.split(' ').tolist())

	#rename columns with meaninful names
	for num in df_split.columns:
		newcol = col + '_' + str(num)
		df_split = df_split.rename(columns={num:newcol})

	df_final = df_notnull.join(df_split)

	return df_final

def trans_space_delimited(df,transcol,groupcols):

	"""Function to split space delimited column, and return a DataFrame containing all 
	items in the column gropued by other dataframe columns of your choice."""

	



